### ISSUE TITLE
Track Current Issues

### ISSUE THREAD

**Issue by Sushrut1101** [OrangeFoxRecovery/device_xiaomi_evergo#1]
# What works?
- [x] Boots
- [x] Touchscreen
- [x] Flashing ZIPs
- [x] Flashing Images
- [x] Mounting Partitions
- [x] External Storage
- [x] Decryption (S Vendor Only)

- [x] Battery Information
- [x] Fastbootd
- [x] ADB (including sideload)
- [x] MTP
- [x] Reboots to System
- [ ] Vibration

**Comment by Sushrut1101** [comment]
Update: On bfa1381, Decryption got fixed!

Commits needed for Decryption:
- b795389
- 569992f
- 3a246e1
- 9e500ce
- ef866ce
- e1b4287
- d10ab23
- bd02769
- bfa1381

**Comment by Sushrut1101** [comment]
4926ff3 fixed touchscreen

**Comment by weaponmasterjax** [comment]
so is the ota function working?
Or it is just not implemented due to the boot hal bug?

**Comment by Sushrut1101** [comment]
> so is the ota function working?
> Or it is just not implemented due to the boot hal bug?

It works now

**Comment by weaponmasterjax** [comment]
Thanks.

**Comment by computerqwq** [comment]
Is the vibration working now?
